<h1>테스트 코드의 구성</h1>

<h2>기능에서의 상황</h2>

* 기능은 주어진 상황에 따라 다르게 동작한다. 예를 들어 아래 기능을 보자.
  * 파일에서 숫자를 읽어와 숫자의 합을 구한다.
  * 한 줄마다 한 개의 숫자를 포함한다.

* 위 기능을 `MathUtils.sum()` 메소드로 구현한다고 가정하자. 아래처럼 `sum()` 메소드에 파일을 인자로 전달할 것이다.   
  `sum()` 메소드는 인자로 전달받는 파일에서 한 줄씩 읽어와 숫자로 변환한 뒤에 합한 값을 결과로 제공하면 된다.
```java
File dataFile = new File("data.txt");
long sum = MathUtils.sum(dataFile);
```

* 하지만 위 기능을 구현하려면 고려할 것이 있다. 먼저 파일이 없는 상황을 처리해야 한다. 데이터를 읽을 파일이 없다면   
  인자가 잘못되었다는 예외를 발생시키거나 문제 상황을 알려줄 수 있는 값을 반환해야 한다. 비슷하게 데이터 중에 숫자가 아닌   
  데이터가 존재하는 경우에도 알맞은 결과를 생성해야 한다.

* 이처럼 주어진 상황에 따라 기능의 실행 결과는 달라진다. 이는 테스트 코드 구조에도 영향을 주게 된다.
<hr/>

<h2>테스트 코드의 구성 요소 : 상황, 실행, 결과 확인</h2>

* 기능은 상황에 따라 결과가 달라진다. 테스트 코드는 기능을 실행하고 그 결과를 확인하므로 상황, 실행, 결과 확인의   
  세 가지 요소로 테스트를 구성할 수 있다. 어떤 상황이 주어지고, 그 상황에서 기능을 실행하고, 실행한 결과를 확인하는   
  세 가지가 테스트 코드의 기본 골격을 이루게 된다.

* 상황, 실행, 결가 확인은 Given, When, Then에 각각 해당한다.

* JUnit에서 상황을 설정하는 방법은 테스트할 대상에 따라 달라진다. 숫자 야구 게임을 예로 들어보자.   
  숫자 야구 게임을 구현한 `BaseballGame` 클래스는 객체를 생성할 때 정답 숫자를 지정한다.   
  이 경우 각 테스트 메소드마다 객체를 생성해서 확인을 설정할 수 있다.
```java
@Test
void exactMatch() {

    // Answer is 456, Given
    BaseballGame game = new BaseballGame("456");

    // When
    Score score = game.guess("456");

    // Then
    assertEquals(3, score.strikes());
    assertEquals(0, score.balls());
}

@Test
void noMatch() {

    // Answer is 123, Given
    BaseballGame game = new BaseballGame("123");

    // When
    Score score = game.guess("456");

    // Then
    assertEquals(0, score.strikes());
    assertEquals(0, score.balls());
}
```

* 또다른 방법은 `@BeforeEach`를 적용한 메소드에서 상황을 설정하는 것이다. 이때는 주로 상황 설정과 관련된 대상을 필드로 보관한다.
```java
private BaseballGame game;

@BeforeEach
void givenGame() {
    game = new BaseballGame("456");
}

@Test
void exactMatch() {
    Score score = game.guess("456");
    assertEquals(3, score.strikes());
    assertEquals(0, score.balls());
}
```

* 상황이 아예 없는 경우도 존재한다. 암호 강도 측정 예시의 경우 결과에 영향을 주는 상황이 존재하지 않으므로   
  테스트는 아래와 같이 기능을 실행하고 결과를 확인하는 코드만 포함하고 있다.
```java
@Test
void meetsAllCriteria_Then_Strong() {
    PasswordStrengthMeter meter = new PasswordStrengthMeter();
    PasswordStrength result = meter.meter("ab12!@AB");
    assertEquals(PasswordStrength.STRONG, result);
}
```

* 실행 결과를 확인하는 쉬운 방법은 리턴 값을 사용하는 것이다. 하지만 실행 결과가 항상 리턴값으로 존재하는 것은 아니다.   
  실행 결과로 예외를 발생시키는 것이 정상인 경우도 있다. 예를 들어 숫자 야구 게임 생성 기능의 테스트 코드는 정답 숫자에   
  동일한 숫자가 존재하면 게임 생성에 실패해야 한다. 이 경우 게임 생성 실패 결과를 표시하기 위해 `BaseballGame` 생성자가   
  `IllegalArgumentException`을 발생시키도록 구현할 수 있다.
```java
@Test
void generateGame_With_DuplicateNumber_Then_Fail() {
    assertThrows(IllegalArgumentException.class,
        () -> new BaseballGame("110")
    );
}
```
<hr/>

<h2>외부 상황과 외부 결과</h2>

* 상황 설정이 테스트 대상으로 국한된 것은 아니다. 상황에는 외부 요인도 존재할 수 있다. 아래 코드를 다시 보자.
```java
File dataFile = new File("data.txt");
long sum = MathUtils.sum(dataFile);
```

* `MathUtils.sum()`을 테스트하려면 파일이 존재하지 않는 상황에서의 결과도 확인해야 한다. 파일이 존재하지 않는 상황을 만들어보자.
```java
@Test
void noDataFile_Then_Exception() {
    File dataFile = new File("AAA");
    assertThrows(IllegalArgumentException.class,
        () -> MathUtils.sum(dataFile)
    );
}
```

* 위 방법이 쉽긴 하지만 항상 테스트에 성공할 것이라는 보장은 없다. 우연히도 해당 파일이 존재할 수도 있기 때문이다.   
  테스트는 실행할 때마다 동일한 결과를 보장해야하는데 우연에 의해 테스트 결과가 달라지면 동일한 결과를 보장할 수 없다.   
  이는 테스트를 신뢰할 수 없게 만들어 테스트 결과를 무시하게 만드는 요인이 될 수 있다.

* 더욱 확실한 방법은 명시적으로 파일이 없는 상황을 만드는 것이다. 아래는 예시이다.
```java
@Test
void noDataFile_Then_Exception() {
    givenNoFile("AAA");

    File dataFile = new File("AAA");
    assertThrows(IllegalArgumentException.class,
        () -> MathUtils.sum(dataFile)
    );
}

private void givenNoFile(String path) {
    File file = new File(path);
    if(file.exists()) {
        boolean deleted = file.delete();
        if(!deleted) throw new RuntimeException("fail givenNoFile : " + path);
    }
}
```

* 위 테스트에서 `givenNoFile()`은 해당 경로에 파일이 검사하는지 검사해서 존재하면 해당 파일을 삭제한다.   
  이렇게 함으로써 테스트가 항상 올바른 상황에서 동작함을 보장할 수 있다.

* 다음으로 파일이 존재하는 상황은 어떻게 만들 수 있을까? 쉬운 방법은 알맞은 위치에 파일을 미리 만들어 두는 것이다.   
  하지만 테스트는 다양한 상황에서 다른 개발자들이 수행할 수 있으므로 이는 올바르지 않은 선택이다.(Git 사용시에는 괜찮다.)

* 아래는 파일을 미리 만들지 않고 테스트 코드에서 상황에 맞는 파일을 생성하는 방법이다.
```java
@Test
void dataFileSumTest2() {
    givenDataFile("target/datafile.txt", "1", "2", "3", "4");
    File dataFile = new File("target/datafile.txt");
    long sum = MathUtils.sum(dataFile);
    assertEquals(10L, sum);
}

private void givenDataFile(String path, String... lines) {
    try {
        Path dataPath = Paths.get(path);
        if(Files.exists(dataPath)) {
            Files.delete(dataPath);
        }
        Files.write(dataPath, Arrays.asList(lines));
    } catch(IOException exception) {
        throw new RuntimeException(exception);
    }
}
```

* 위 방법의 장점은 테스트 코드 안에 필요한 것이 다 있다는 것이다. 테스트 코드에서 상황을 명시적으로 구성하기 때문에   
  테스트 내용을 이해하기 위해 많은 파일들을 볼 필요가 없다.

* 테스트 대상이 아닌 외부에서 결과를 확인해야 할 때도 있다. 예를 들어 처리 결과를 지정한 경로의 파일에 저장하는 기능을 생각해보자.   
  이 기능을 실행한 결과를 검증하려면 해당 경로에 파일이 원하는 내용으로 만들어졌는지 확인해야 한다.

<h3>외부 상태가 테스트 결과에 영향을 주지 않게 하기</h3>

* 테스트 코드는 한 번만 실행하고 끝나지 않는다. TDD를 진행하는 동안에도 계속 실행하고 끝난 이후에도 반복적으로 테스트를 실행해서   
  문제가 없는지 검증한다. 그렇기 때문에 테스트는 언제 실행해도 항상 정상적으로 동작하는 것이 중요하다. 간헐적으로 실패하거나 다른 테스트   
  다음에 실행해야 성공하면 테스트 결과를 믿을 수 없게 된다.

* 회원 가입 기능을 예로 들어보자. 회원 가입 기능 테스트는 다음을 포함한다.
  * 중복된 ID가 이미 존재하면 가입 실패
  * 모든 조건을 충족하면 가입 성공

* 위의 두 테스트를 아래와 같이 작성했다고 하자.
```java
@Test
void duplicatedIdTest() {
    RegisterRequest request = new RegisterRequest("sangwoo", "상우");
    assertThrows(DuplicateIdException.class,
        () -> registerService.register(request)
    );
}

@Test
void registerSuccess() {
    RegisterRequest request = new RegisterRequest("sangwoo2", "상우2");
    registerService.register(request);
    Member member = membersRepository.findById("sangwoo2");
    assertEquals("상우2", member.getName());
}
```

* 위 코드 중 `duplicatedIdTest()`를 검증하려면 DB의 회원 테이블에 아이디가 "sangwoo"인 데이터를 미리 추가해야한다.   
  그래야 테스트가 올바르게 동작한다.

* 아이디가 "sangwoo2"인 데이터가 없는 상태에서 `registerSuccess()`를 실행했더니 통과했다고 하자. 이 테스트에 성공하면 DB의   
  회원 테이블에 아이디가 "sangwoo2"인 데이터가 생성된다. 이 상태에서 다시 `registerSuccess()`를 수행하면 아이디 중복으로   
  테스트에 실패한다. 즉, DB 데이터의 상태에 따라 테스트가 성공하기도 하고 실패하기도 하는 것이다.

* 이렇게 외부 상태에 따라 테스트의 성공 여부가 바뀌지 않으려면 테스트 실행 전에 외부를 원하는 상태로 만들거나 테스트 실행 후에   
  외부 상태를 원래대로 돌려놓아야 한다.

<h3>외부 상태와 테스트 어려움</h3>

* 상황과 결과에 영향을 주는 외부 요인은 파일, DBMS, 외부 서버 등 다양하다. 이들 외부 환경을 테스트에 맞게 구성하는 것이   
  항상 가능한 것은 아니다. 자동이체 등록 기능을 생각해보자. 이 기능은 입력받은 계좌가 올바른지 확인해야 한다. 이를 위해 금융 회사에서   
  제공하는 REST API를 사용한다면 자동이체 등록 기능에 대한 테스트는 다음 상황에서의 결과를 확인할 수 있어야 한다.
  * REST API 응답 결과가 유효한 계좌 번호인 상황
  * REST API 응답 결과가 유효하지 않은 계좌 번호인 상황
  * REST API 서버에 연결할 수 없는 상황
  * REST API 응답이 Timeout 되는 상황

* 위와 같은 상황들은 개발자가 해결할 수 없는 상황이다.

* 실행 결과가 외부 시스템에 기록되는 경우도 있다. 예를 들어 외부 택배사에 배송 정보를 전달하기 위해 택배사가 제공한 DB 테이블을 사용한다 하자.   
  주문이 들어오면 택배사가 제공한 DB 테이블에 필요한 데이터를 추가하는 방식으로 배송 정보를 전달했다.   
  동일한 테스트를 여러번 수행할 수 있으려면 택배사가 제공한 DB 테이블에서 데이터를 삭제할 수 있어야 하는데 택배사는 해당 테이블에 대해   
  INSERT와 SELECT 권한만 주고 DELETE 권한은 주지 않았다.

* 이처럼 테스트 대상이 아닌 외부 요인은 테스트 코드에서 다루기 힘든 존재이다. 외부 상황은 테스트 코드에서 마음애로 제어할 수 없는   
  경우가 있다. 또한 테스트 코드에서 생성한 외부 결과를 마음대로 초기화하기 힘들 때도 있다. 이렇게 테스트 대상의 상황과 결과에   
  외부 요인이 관여할 경우 `대역`을 사용하면 테스트 작성이 쉬워진다. `대역`은 테스트 대상이 의존하는 대상의 실제 구현을   
  대신하는 구현인데, 이 `대역`을 통해서 외부 상황이나 결과를 대체할 수 있다.
<hr/>